#from mlp import Mlp
from vision import Vision
import numpy as np 
from simulation import Simulation
from ga import Ga
from mlp import Mlp 

NUMBER_CHROMOSOMES = 10
EPOCHS = 10

if __name__ == '__main__':
#	mlp = Mlp()
#	train = np.array([[50., 50., 0.],
#			 			[25., 25., 1.],
#			 			[15., 25., 1.],
#Y			 			[30., 30., 0.],])

#	mlp.set_train(train[:,0:2], train[:,2])
#	mlp.train()
#	mlp.predict(np.array([[50.,50.]]))
	'''
	vision = Vision()
	print('start')
	vision.get_train_imgs()
	vision.get_all_parameters()
	#vision.get_bird('images/1.png')
	'''
	'''
	vision.get_borders('images/29.png')
	last_px, pxright = vision.find_borders_values()
	vision.get_pipe_pixel(last_px, pxright, 'images/processed/0.png')
	vision.get_center('images/processed/0.png')
	'''
	"""
	mlp = Mlp()
	mlp.load_mlp()
	vis = Vision()
	vis.play(mlp)
	"""

	

	ga = Ga(NUMBER_CHROMOSOMES)
	ga.set_train_set([
		#  ['images/processed/18.png'],
		#  ['images/processed/19.png'],
		#  ['images/processed/20.png'],
		#  ['images/processed/21.png'],
		#  ['images/processed/22.png'],
		#  ['images/processed/23.png'],
		#  ['images/processed/24.png'],
		#  ['images/processed/25.png'],
		#  ['images/processed/26.png'],
		#  ['images/processed/27.png'],
		#  ['images/processed/28.png'],
		#  ['images/processed/29.png'],
		#  ['images/processed/30.png'],
		#  ['images/processed/31.png'],
		#  ['images/processed/32.png'],
		#  ['images/processed/33.png'],
		#  ['images/processed/34.png'],
		#  ['images/processed/35.png'],
		#  ['images/processed/36.png'],
		#  ['images/processed/37.png'],
		#  ['images/processed/38.png'],
		#  ['images/processed/39.png'],
		#  ['images/processed/40.png'],
		#  ['images/processed/41.png'],
		#  ['images/processed/42.png'],
		#  ['images/processed/43.png'],
		#  ['images/processed/44.png'],
		#  ['images/processed/45.png'],
		#  ['images/processed/46.png'],
		#  ['images/processed/47.png'],
		#  ['images/processed/48.png'],
		#  ['images/processed/49.png'],
		#  ['images/processed/50.png'],
		#  ['images/processed/51.png'],
		#  ['images/processed/52.png'],
		#  ['images/processed/53.png'],
		#  ['images/processed/54.png'],
		#  ['images/processed/55.png'],
		# ['images/processed/56.png'],
		# ['images/processed/57.png'],
		# ['images/processed/58.png'],
		# ['images/processed/59.png'],
		# ['images/processed/60.png'],
		# ['images/processed/61.png'],
		# ['images/processed/62.png'],
		# ['images/processed/63.png'],
		# ['images/processed/64.png'],
		# ['images/processed/65.png'],
		# ['images/processed/66.png'],
		# ['images/processed/67.png'],
		# ['images/processed/68.png'],
		# ['images/processed/69.png'],
		# ['images/processed/70.png'],
		# ['images/processed/71.png'],
		# ['images/processed/72.png'],
		# ['images/processed/73.png'],
		# ['images/processed/74.png'],
		# ['images/processed/75.png'],
		# ['images/processed/76.png'],
		# ['images/processed/77.png'],
		# ['images/processed/78.png'],
		# ['images/processed/79.png'],
		# ['images/processed/80.png'],
		# ['images/processed/81.png'],
		# ['images/processed/82.png'],
		['images/processed/83.png'],
		['images/processed/84.png'],
		['images/processed/85.png'],
		['images/processed/86.png'],
		['images/processed/87.png'],
		['images/processed/88.png'],
		['images/processed/89.png'],
		['images/processed/90.png'],
		['images/processed/91.png'],
		['images/processed/92.png'],
		['images/processed/93.png'],
		['images/processed/94.png'],
		['images/processed/95.png'],
		['images/processed/96.png'],
		['images/processed/97.png'],
		['images/processed/98.png'],
		['images/processed/99.png'],
		['images/processed/100.png'],
		['images/processed/101.png'],
		['images/processed/102.png'],
		['images/processed/103.png'],
		['images/processed/104.png'],
		['images/processed/105.png'],
		['images/processed/106.png'],
		['images/processed/107.png'],
		['images/processed/108.png'],
		['images/processed/109.png'],
		['images/processed/110.png'],
		['images/processed/111.png'],
		['images/processed/112.png'],
		['images/processed/113.png'],
		['images/processed/114.png'],
		['images/processed/115.png'],
		['images/processed/116.png'],
		['images/processed/117.png'],
		['images/processed/118.png'],
		['images/processed/119.png'],
		['images/processed/120.png'],
		['images/processed/121.png'],
		 ['images/processed/122.png'],
		 ['images/processed/123.png'],
		 ['images/processed/124.png'],
		 ['images/processed/125.png'],
		 ['images/processed/126.png'],
		 ['images/processed/127.png'],
		 ['images/processed/128.png'],
		 ['images/processed/129.png'],
		 ['images/processed/130.png'],
		 ['images/processed/131.png'],
		 ['images/processed/132.png'],
		 ['images/processed/133.png'],
		 ['images/processed/134.png'],
		 ['images/processed/135.png'],
		 ['images/processed/136.png'],
		 ['images/processed/137.png'],
		 ['images/processed/138.png'],
		 ['images/processed/139.png'],
		 ['images/processed/140.png'],
		 ['images/processed/141.png'],
		 ['images/processed/142.png'],
		 ['images/processed/143.png'],
		 ['images/processed/144.png'],
		 ['images/processed/145.png'],
		 ['images/processed/146.png'],
		 ['images/processed/147.png'],
		 ['images/processed/148.png'],
		 ['images/processed/149.png'],
		 ['images/processed/150.png'],
		 ['images/processed/151.png'],
		 ['images/processed/152.png'],
		 ['images/processed/153.png'],
		 ['images/processed/154.png'],
		 ['images/processed/155.png'],
		['images/processed/156.png'],
		['images/processed/157.png'],
		['images/processed/158.png'],
		['images/processed/159.png'],
		['images/processed/160.png'],
		['images/processed/161.png'],
		['images/processed/162.png'],
		['images/processed/163.png'],
		['images/processed/164.png'],
		['images/processed/165.png'],
		['images/processed/166.png'],
		['images/processed/167.png'],
		['images/processed/168.png'],
		['images/processed/169.png'],
		['images/processed/170.png'],
		['images/processed/171.png'],
		['images/processed/172.png'],
		['images/processed/173.png'],
		['images/processed/174.png'],
		['images/processed/175.png'],
		['images/processed/176.png'],
		['images/processed/177.png'],
		['images/processed/178.png'],
		['images/processed/179.png'],
		['images/processed/180.png'],
		['images/processed/181.png'],
		['images/processed/182.png'],
		['images/processed/183.png'],
		['images/processed/184.png'],
		['images/processed/185.png'],
		['images/processed/186.png'],
		['images/processed/187.png'],
		['images/processed/188.png'],
		['images/processed/189.png'],
		['images/processed/190.png'],
		['images/processed/191.png'],
		['images/processed/192.png'],
		['images/processed/193.png'],
		['images/processed/194.png'],
		['images/processed/195.png'],
		['images/processed/196.png'],
		['images/processed/197.png'],
		['images/processed/198.png'],
		['images/processed/199.png'],
		['images/processed/200.png'],
		['images/processed/201.png'],
		['images/processed/202.png'],
		['images/processed/203.png'],
		['images/processed/204.png'],
		['images/processed/205.png'],
		['images/processed/206.png'],
		['images/processed/207.png'],
		['images/processed/208.png'],
		['images/processed/209.png'],
		['images/processed/210.png'],
		['images/processed/211.png'],
		['images/processed/212.png'],
		['images/processed/213.png'],
		['images/processed/214.png'],
		['images/processed/215.png'],
		['images/processed/216.png'],
		['images/processed/217.png'],
		['images/processed/218.png'],
		['images/processed/219.png'],
		['images/processed/220.png'],
		['images/processed/221.png'],
		 ['images/processed/222.png'],
		 ['images/processed/223.png'],
		 ['images/processed/224.png'],
		 ['images/processed/225.png'],
		 ['images/processed/226.png'],
		 ['images/processed/227.png'],
		 ['images/processed/228.png'],
		 ['images/processed/229.png'],
		 ['images/processed/230.png'],
		 ['images/processed/231.png'],
		 ['images/processed/232.png'],
		 ['images/processed/233.png'],
		 ['images/processed/234.png'],
		 ['images/processed/235.png'],
		 ['images/processed/236.png'],
		 ['images/processed/237.png'],
		 ['images/processed/238.png'],
		 ['images/processed/239.png'],
		 ['images/processed/240.png'],
		 ['images/processed/241.png'],
		 ['images/processed/242.png'],
		 ['images/processed/243.png'],
		 ['images/processed/244.png'],
		 ['images/processed/245.png'],
		 ['images/processed/246.png'],
		 ['images/processed/247.png'],
		 ['images/processed/248.png'],
		 ['images/processed/249.png'],
		 ['images/processed/250.png'],
		 ['images/processed/251.png'],
		 ['images/processed/252.png'],
		 ['images/processed/253.png'],
		 ['images/processed/254.png'],
		 ['images/processed/255.png'],
		['images/processed/256.png'],
		['images/processed/257.png'],
		['images/processed/258.png'],
		['images/processed/259.png'],
		['images/processed/260.png'],
		['images/processed/261.png'],
		['images/processed/262.png'],
		['images/processed/263.png'],
		['images/processed/264.png'],
		['images/processed/265.png'],
		['images/processed/266.png'],
		['images/processed/267.png'],
		['images/processed/268.png'],
		['images/processed/269.png'],
		['images/processed/270.png'],
		['images/processed/271.png'],
		['images/processed/272.png'],
		['images/processed/273.png'],
		['images/processed/274.png'],
		['images/processed/275.png'],
		['images/processed/276.png'],
		['images/processed/277.png'],
		['images/processed/278.png'],
		['images/processed/279.png'],
		['images/processed/280.png'],
		['images/processed/281.png'],
		['images/processed/282.png'],
		['images/processed/283.png'],
		['images/processed/284.png'],
		['images/processed/285.png'],
		['images/processed/286.png'],
		['images/processed/287.png'],
		['images/processed/288.png'],
		['images/processed/289.png'],
		['images/processed/290.png'],
		['images/processed/291.png'],
		['images/processed/292.png'],
		['images/processed/293.png'],
		['images/processed/294.png'],
		['images/processed/295.png'],
		['images/processed/296.png'],
		['images/processed/297.png'],
		['images/processed/298.png'],
		['images/processed/299.png'],
		['images/processed/300.png'],
		['images/processed/301.png'],
		['images/processed/302.png'],
		['images/processed/303.png'],
		['images/processed/304.png'],
		['images/processed/305.png'],
		['images/processed/306.png'],
		['images/processed/307.png'],
		['images/processed/308.png'],
		['images/processed/309.png'],
		['images/processed/310.png'],
		['images/processed/311.png'],
		['images/processed/312.png'],
		['images/processed/313.png'],
		['images/processed/314.png'],
		['images/processed/315.png'],
		['images/processed/316.png'],
		['images/processed/317.png'],
		['images/processed/318.png'],
		['images/processed/319.png'],
		['images/processed/320.png'],
		['images/processed/321.png'],
		 ['images/processed/322.png'],
		 ['images/processed/323.png'],
		 ['images/processed/324.png'],
		 ['images/processed/325.png'],
		 ['images/processed/326.png'],
		 ['images/processed/327.png'],
		 ['images/processed/328.png'],
		 ['images/processed/329.png'],
		 ['images/processed/330.png'],
		 ['images/processed/331.png'],
		 ['images/processed/332.png'],
		 ['images/processed/333.png'],
		 ['images/processed/334.png'],
		 ['images/processed/335.png'],
		 ['images/processed/336.png'],
		 ['images/processed/337.png'],
		 ['images/processed/338.png'],
		 ['images/processed/339.png'],
		 ['images/processed/340.png'],
		 ['images/processed/341.png'],
		 ['images/processed/342.png'],
		 ['images/processed/343.png'],
		 ['images/processed/344.png'],
		 ['images/processed/345.png'],
		 ['images/processed/346.png'],
		 ['images/processed/347.png'],
		 ['images/processed/348.png'],
		 ['images/processed/349.png'],
		 ['images/processed/350.png'],
		 ['images/processed/351.png'],
		 ['images/processed/352.png']
		])
	ga.run(EPOCHS)

	'''
	sim = Simulation()
	sim.update()
	sim.jump()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.jump()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	sim.update()
	'''
